# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2f0a3218e9fc6f062fe5ec9ebab35e7e20f2f0162af666e2ba509bedf061a3e4fc7b7607fc10175aefe54b2451fc779bb81c67571a7771b73708a7b97e157a1

test:
  secret_key_base: 66d1b077632016912258670c1f72525ddcbdd416337e8d32d9b47a64ea9ae50036b3fa1d89390052b4a59bd31f10d0daff742561f262095a5ee59c723a54cc2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
